# Generated by Django 4.0 on 2022-01-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('sellername', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('situation', models.CharField(max_length=50)),
            ],
        ),
    ]
